pull datalake-spark2 and refactor indexer
Ferlab-Ste-Justine/cqdg-etl-indexer pull request #2
Opened 2021-05-20 18:45 UTC by botekchristophe

2021-05-21 15:01 UTC, creativeyann17 requested changes

2021-05-21 15:01 UTC, creativeyann17 commented on src/main/scala/ca/cqdg/index/IndexerV2.scala
> +  new Indexer(jobType, path(templateFileName), alias, oldRelease, newRelease).run(inputDf)
`Exception in thread "main" java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.` at bio.ferlab.datalake.spark2.elasticsearch.ElasticSearchClient.setTemplate(ElasticSearchClient.scala:87)

2021-05-21 15:12 UTC, creativeyann17 commented on src/main/scala/ca/cqdg/index/IndexerV2.scala
> +    this.getClass.getResource(str).getFile
I have same issue with indexer-v1 now, try to understand why it worked before

2021-05-21 15:21 UTC, creativeyann17 commented on src/main/scala/ca/cqdg/index/IndexerV2.scala
> +    this.getClass.getResource(str).getFile
I confirm, it's because .json files have been moved, the following line has to be changed as well:
ESIndicesManager:createIndex
    val configSource:Source = Source.fromInputStream(getClass.getClassLoader.getResourceAsStream(indexConfig), "UTF-8")

2021-05-21 15:52 UTC, botekchristophe commented on src/main/scala/ca/cqdg/index/IndexerV2.scala
> +    this.getClass.getResource(str).getFile
good catch, my bad.
In the futur these files should be on s3. this works only when executing the code locally

2021-05-21 15:52 UTC, botekchristophe commented on src/main/scala/ca/cqdg/index/IndexerV2.scala
> +  new Indexer(jobType, path(templateFileName), alias, oldRelease, newRelease).run(inputDf)
thanks I'll check this

2021-05-25 13:52 UTC, creativeyann17 approved these changes

2021-05-25 13:55 UTC, merged